openapi: 3.0.3
info:
  title: Weather Sender API
  description: API for my Weather Update Sender system
  version: "${project.version}"
servers:
  - url: 'http'

paths:
  '/weatherReport/{date}':
    get:
      tags:
        - Weather-Service
      operationId: getWeatherReport
      summary: Get Weather Report for given date
      parameters:
        - in: path
          name: date
          schema:
            $ref: '#/components/parameters/Date'
          required: true
      responses:
        '200':
          description: Successfully found a weather report for the required date
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/WeatherReport'
        '400':
          description: Bad request - probably means the date is not formatted correctly
        '404':
          description: The weather report for the requested date does not exist
        '422':
          description: The weather report for the requested date does exist and is on the system, but for some reason is invalid
  '/weatherReport':
    post:
      tags:
        - Weather-Service
      operationId: generateWeatherReport
      summary: Generate a weather report for the current day
      responses:
        '201':
          description: The weather report was successfully fully generated and is being returned
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/WeatherReport'
        '500':
          description: The weather report was not successfully generated

components:
  parameters:
    Date:
      name: Date
      schema:
        type: string
      required: true
      description: Following the format YYYY-mm-dd
      example: '2024-03-01'
  schemas:
    WeatherReport:
      name: Weather Report
      type: string
      description: Structured string of the weather report

